// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEXPK1H8xlPZ-bvrbuxJqNWUR9pMoGfo',
    appId: '1:1000092547089:web:48c3d43baab292cfab59b0',
    messagingSenderId: '1000092547089',
    projectId: 'hobby-hub-88eac',
    authDomain: 'hobby-hub-88eac.firebaseapp.com',
    storageBucket: 'hobby-hub-88eac.firebasestorage.app',
    measurementId: 'G-LGZL6KHTFT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLEnI9ek1fscQ2roMqvC2C-H-onCd06OU',
    appId: '1:1000092547089:ios:a536ce85dbf1bbd1ab59b0',
    messagingSenderId: '1000092547089',
    projectId: 'hobby-hub-88eac',
    storageBucket: 'hobby-hub-88eac.firebasestorage.app',
    androidClientId: '1000092547089-7pctasfagbjq08n8kkbo67q71e4l5aph.apps.googleusercontent.com',
    iosClientId: '1000092547089-82s03maapeirsbf20nrp8sejjs4jeu1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbyHubv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgEXPK1H8xlPZ-bvrbuxJqNWUR9pMoGfo',
    appId: '1:1000092547089:web:edd98f7627a79349ab59b0',
    messagingSenderId: '1000092547089',
    projectId: 'hobby-hub-88eac',
    authDomain: 'hobby-hub-88eac.firebaseapp.com',
    storageBucket: 'hobby-hub-88eac.firebasestorage.app',
    measurementId: 'G-FNBD72B95D',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLEnI9ek1fscQ2roMqvC2C-H-onCd06OU',
    appId: '1:1000092547089:ios:a536ce85dbf1bbd1ab59b0',
    messagingSenderId: '1000092547089',
    projectId: 'hobby-hub-88eac',
    storageBucket: 'hobby-hub-88eac.firebasestorage.app',
    androidClientId: '1000092547089-7pctasfagbjq08n8kkbo67q71e4l5aph.apps.googleusercontent.com',
    iosClientId: '1000092547089-82s03maapeirsbf20nrp8sejjs4jeu1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbyHubv2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbxSpPsAgxI9qr25jQUTqAmO-kwBn38A',
    appId: '1:1000092547089:android:8e4d2e7b5c2f2172ab59b0',
    messagingSenderId: '1000092547089',
    projectId: 'hobby-hub-88eac',
    storageBucket: 'hobby-hub-88eac.firebasestorage.app',
  );
}
